#55 Added StrongDefaultValue for ValueArgument
j-maly/CommandLineParser pull request #57
Opened 2018-01-19 12:51 UTC by eapyl

As it is described in #55

2018-10-31 15:52 UTC, StefH requested changes
Hello @eapyl 
Thanks for this PR, can you please take a look at the comments?

2018-10-31 15:52 UTC, StefH commented on src/CommandLineArgumentsParser/Arguments/IArgumentWithForceDefaultValue.cs
> +    public interface IArgumentWithForceDefaultValue
Force or Forced ?

```suggestion
    public interface IArgumentWithForcedDefaultValue
```

2018-10-31 15:52 UTC, StefH commented on src/CommandLineArgumentsParser/Arguments/ValueArgument.cs
> +        public TValue StrongDefaultValue { get; set; }
Suggestion would be use Forced instead of Strong:
```suggestion
        public TValue ForcedDefaultValue { get; set; }
```

2019-06-02 13:36 UTC, StefH approved these changes

2019-06-02 13:36 UTC, merged

2019-06-30 15:03 UTC, twpol commented
I think this change means that many (all?) existing uses of `DefaultValue` now have to use `ForcedDefaultValue`, which caused me quite a lot of confusion when updating the version of CommandLineParser just now. I can raise an issue with full details and code if you need it.

2019-06-30 20:15 UTC, StefH commented
Sorry for the confusion. Please raise an issue with the usage differences for before/after this code.

2019-06-30 20:15 UTC, StefH commented
Sorry for the confusion. Please raise an issue with the usage differences for before/after this code.

2019-07-18 05:12 UTC, alexandre-lecoq commented
I have the same issue. However, my understanding is that it's not really a bug, but rather an unconscious and unadvertised breaking change.
Also could not find anything about `ForceDefaultValue` in the documentation.

Basically, i had this code :
```
        [ValueArgument(
            typeof(int),
            "connectiontimeout",
            DefaultValue = 5,
            Description = "The time to wait for a connection to open.",
            FullDescription = "The time (in seconds) to wait for a connection to open. The default value is 5 seconds.",
            Example = "15")]
        public int ConnectionTimeout { get; set; }
```
This code would behave like this : 
* No "--connectiontimeout" passed => ConnectionTimeout = 5
* "--connectiontimeout 10" passed => ConnectionTimeout = 10

Now with the introduction of  `ForceDefaultValue` the code behaves like :
* No "--connectiontimeout" passed => ConnectionTimeout = 0
* "--connectiontimeout 10" passed => ConnectionTimeout = 10

This is how it broke my application.
My understanding, is that there is a change of semantic of `DefaultValue`.
It was the default value for both the lack of passed parameter and the lack of value for a passed parameter.
It seems to me, now, those 2 cases are split :
* `ForceDefaultValue` is used for the lack of passed parameter
* `DefaultValue` is used for the lack of value for a passed parameter

Therefore if I understand correcly, in the latest version, I to change my code to :
```
        [ValueArgument(
            typeof(int),
            "connectiontimeout",
            DefaultValue = 5,
            ForcedDefaultValue = 5,
            Description = "The time to wait for a connection to open.",
            FullDescription = "The time (in seconds) to wait for a connection to open. The default value is 5 seconds.",
            Example = "15")]
        public int ConnectionTimeout { get; set; }
```
That is, for ValueArgument, if I want to keep the old behavior, wherever I have `DefaultValue`, I now have to also add `ForcedDefaultValue`.

Can you confirm ?

2019-07-18 06:11 UTC, StefH commented
Thank you for this information. I will try to understand and investigate the code and see if I can bring the old behaviour back.

2019-07-18 17:34 UTC, alexandre-lecoq commented
I think the cause is here :
https://github.com/j-maly/CommandLineParser/blob/40120ac02a670dae0ace4e21103d97be370ad46e/src/CommandLineArgumentsParser/Arguments/ValueArgument.cs#L428

2019-07-18 19:09 UTC, alexandre-lecoq commented
I proposed a fix in PR #68